name: btk_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  uuid: ^4.5.1

  #Toast
  fluttertoast: ^8.2.8
  #Network
  web_socket_channel: ^2.2.0

  kartal: ^4.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/images/image3.jpg
    - assets/images/image2.jpg
    - assets/images/image1.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/image6.jpg
    - assets/images/image7.jpg
    - assets/images/image8.jpg
    - assets/images/image9.jpg
    - assets/images/image10.jpg
