// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWyh-cAs0D4wyxbUDE0yUHsU819qywDs',
    appId: '1:295406598723:web:6e1bf3d641137ae1d172f6',
    messagingSenderId: '295406598723',
    projectId: 'btkproject-75d41',
    authDomain: 'btkproject-75d41.firebaseapp.com',
    storageBucket: 'btkproject-75d41.appspot.com',
    measurementId: 'G-11VG6Z2B55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrMNV79za-o77ZhA93xgXCyaSLZCtmTc',
    appId: '1:295406598723:android:6895ba3ece6eb45dd172f6',
    messagingSenderId: '295406598723',
    projectId: 'btkproject-75d41',
    storageBucket: 'btkproject-75d41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9MNBN-AuV6JaVOjmsFuXhQYzWhx8thrk',
    appId: '1:295406598723:ios:8508116d7f596590d172f6',
    messagingSenderId: '295406598723',
    projectId: 'btkproject-75d41',
    storageBucket: 'btkproject-75d41.appspot.com',
    iosBundleId: 'com.example.btkProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9MNBN-AuV6JaVOjmsFuXhQYzWhx8thrk',
    appId: '1:295406598723:ios:8508116d7f596590d172f6',
    messagingSenderId: '295406598723',
    projectId: 'btkproject-75d41',
    storageBucket: 'btkproject-75d41.appspot.com',
    iosBundleId: 'com.example.btkProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkWyh-cAs0D4wyxbUDE0yUHsU819qywDs',
    appId: '1:295406598723:web:9573c7dbfd79aa47d172f6',
    messagingSenderId: '295406598723',
    projectId: 'btkproject-75d41',
    authDomain: 'btkproject-75d41.firebaseapp.com',
    storageBucket: 'btkproject-75d41.appspot.com',
    measurementId: 'G-8MEW1X3DZ2',
  );
}
