// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mCTdxw_1MkY-vSokXNHv3p5eFByVmVY',
    appId: '1:175815746346:web:14e817003c1bd0ef2b3453',
    messagingSenderId: '175815746346',
    projectId: 'btk-hackathon',
    authDomain: 'btk-hackathon.firebaseapp.com',
    storageBucket: 'btk-hackathon.appspot.com',
    measurementId: 'G-G2WYEYLPF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDho4m0c1fkLrQR2BPX7tPdmyE3FCimh34',
    appId: '1:175815746346:android:f4addfc07534d3222b3453',
    messagingSenderId: '175815746346',
    projectId: 'btk-hackathon',
    storageBucket: 'btk-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdMnxDjsYje5z0wkTIhtwHJ0YPM6yo_I0',
    appId: '1:175815746346:ios:c8c7f5cf49ab31e72b3453',
    messagingSenderId: '175815746346',
    projectId: 'btk-hackathon',
    storageBucket: 'btk-hackathon.appspot.com',
    iosBundleId: 'com.example.btkHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdMnxDjsYje5z0wkTIhtwHJ0YPM6yo_I0',
    appId: '1:175815746346:ios:c8c7f5cf49ab31e72b3453',
    messagingSenderId: '175815746346',
    projectId: 'btk-hackathon',
    storageBucket: 'btk-hackathon.appspot.com',
    iosBundleId: 'com.example.btkHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1mCTdxw_1MkY-vSokXNHv3p5eFByVmVY',
    appId: '1:175815746346:web:98303afe63a551522b3453',
    messagingSenderId: '175815746346',
    projectId: 'btk-hackathon',
    authDomain: 'btk-hackathon.firebaseapp.com',
    storageBucket: 'btk-hackathon.appspot.com',
    measurementId: 'G-3DS642YG84',
  );
}
